In [1]:
import numpy as np

In [8]:
x = np.array(range(1,10))
print(x)
print(x[3:8])

[1 2 3 4 5 6 7 8 9]
[4 5 6 7 8]


In [11]:
x = [1,2,3,4]
x[:-1]

[1, 2, 3]

In [12]:
x = [1,2,3,4]
x[-1]

4

In [20]:
import numpy as np
x =np.arange(10)
cond = x < 3
x[cond] = 0
print(x)
print(cond)
print(x[cond])

[0 0 0 3 4 5 6 7 8 9]
[ True  True  True False False False False False False False]
[0 0 0]


In [30]:
a = np.array([[1,2],[4,5]], dtype="int64")
b = np.identity(2, dtype="int64")
c = a.dot(b)
c


array([[1, 2],
       [4, 5]])

In [33]:
a = [1,2,3]
b =['one', 'two', 'three']
u = zip(a,b)
dict(u)

{1: 'one', 2: 'two', 3: 'three'}

In [39]:
import pandas as pd
df = pd.read_csv("data.csv")
# df.loc[df.name == "fanny"]
df.loc[:2]
#print(df.apply(len,axis=1))
# def old_or_young(data):
#     return 'old' if data['age'] > 40 else 'young'
# df['comment'] = df.apply(old_or_young,axis=1)
# g_comment = df.groupby(['comment'])
# g_comment.size()
# g_comment.get_group("old")
# g_comment.sum()

name  age
0  victor   41
1   peter   38
2   fanny   46